"use strict";
// https://en.wikipedia.org/wiki/Code_page_437
// https://en.wikipedia.org/wiki/Block_Elements
// https://en.wikipedia.org/wiki/Box-drawing_character
Object.defineProperty(exports, "__esModule", { value: true });
exports.Chars = void 0;
var Chars;
(function (Chars) {
    Chars[Chars["SMILEY"] = 1] = "SMILEY";
    Chars[Chars["INVERSE_SMILEY"] = 2] = "INVERSE_SMILEY";
    Chars[Chars["HEART"] = 3] = "HEART";
    Chars[Chars["DIAMOND"] = 4] = "DIAMOND";
    Chars[Chars["CLUB"] = 5] = "CLUB";
    Chars[Chars["SPADE"] = 6] = "SPADE";
    Chars[Chars["BULLET"] = 7] = "BULLET";
    Chars[Chars["INVERSE_BULLET"] = 8] = "INVERSE_BULLET";
    Chars[Chars["LIGHT_SHADE"] = 176] = "LIGHT_SHADE";
    Chars[Chars["MEDIUM_SHADE"] = 177] = "MEDIUM_SHADE";
    Chars[Chars["DARK_SHADE"] = 178] = "DARK_SHADE";
    Chars[Chars["BOX_SINGLE_VERTICAL"] = 179] = "BOX_SINGLE_VERTICAL";
    Chars[Chars["BOX_SINGLE_VERTICAL_AND_SINGLE_LEFT"] = 180] = "BOX_SINGLE_VERTICAL_AND_SINGLE_LEFT";
    Chars[Chars["BOX_DOUBLE_VERTICAL_AND_DOUBLE_LEFT"] = 185] = "BOX_DOUBLE_VERTICAL_AND_DOUBLE_LEFT";
    Chars[Chars["BOX_DOUBLE_VERTICAL"] = 186] = "BOX_DOUBLE_VERTICAL";
    Chars[Chars["BOX_DOUBLE_DOWN_AND_DOUBLE_LEFT"] = 187] = "BOX_DOUBLE_DOWN_AND_DOUBLE_LEFT";
    Chars[Chars["BOX_DOUBLE_UP_AND_DOUBLE_LEFT"] = 188] = "BOX_DOUBLE_UP_AND_DOUBLE_LEFT";
    Chars[Chars["BOX_SINGLE_DOWN_AND_SINGLE_LEFT"] = 191] = "BOX_SINGLE_DOWN_AND_SINGLE_LEFT";
    Chars[Chars["BOX_SINGLE_UP_AND_SINGLE_RIGHT"] = 192] = "BOX_SINGLE_UP_AND_SINGLE_RIGHT";
    Chars[Chars["BOX_SINGLE_HORIZONTAL_AND_SINGLE_UP"] = 193] = "BOX_SINGLE_HORIZONTAL_AND_SINGLE_UP";
    Chars[Chars["BOX_SINGLE_HORIZONTAL_AND_SINGLE_DOWN"] = 194] = "BOX_SINGLE_HORIZONTAL_AND_SINGLE_DOWN";
    Chars[Chars["BOX_SINGLE_VERTICAL_AND_SINGLE_RIGHT"] = 195] = "BOX_SINGLE_VERTICAL_AND_SINGLE_RIGHT";
    Chars[Chars["BOX_SINGLE_HORIZONTAL"] = 196] = "BOX_SINGLE_HORIZONTAL";
    Chars[Chars["BOX_SINGLE_VERTICAL_AND_SINGLE_HORIZONTAL"] = 197] = "BOX_SINGLE_VERTICAL_AND_SINGLE_HORIZONTAL";
    Chars[Chars["BOX_DOUBLE_UP_AND_DOUBLE_RIGHT"] = 200] = "BOX_DOUBLE_UP_AND_DOUBLE_RIGHT";
    Chars[Chars["BOX_DOUBLE_DOWN_AND_DOUBLE_RIGHT"] = 201] = "BOX_DOUBLE_DOWN_AND_DOUBLE_RIGHT";
    Chars[Chars["BOX_DOUBLE_HORIZONTAL_AND_DOUBLE_UP"] = 202] = "BOX_DOUBLE_HORIZONTAL_AND_DOUBLE_UP";
    Chars[Chars["BOX_DOUBLE_HORIZONTAL_AND_DOUBLE_DOWN"] = 203] = "BOX_DOUBLE_HORIZONTAL_AND_DOUBLE_DOWN";
    Chars[Chars["BOX_DOUBLE_VERTICAL_AND_DOUBLE_RIGHT"] = 204] = "BOX_DOUBLE_VERTICAL_AND_DOUBLE_RIGHT";
    Chars[Chars["BOX_DOUBLE_HORIZONTAL"] = 205] = "BOX_DOUBLE_HORIZONTAL";
    Chars[Chars["BOX_DOUBLE_VERTICAL_AND_DOUBLE_HORIZONTAL"] = 206] = "BOX_DOUBLE_VERTICAL_AND_DOUBLE_HORIZONTAL";
    Chars[Chars["BOX_SINGLE_UP_AND_SINGLE_LEFT"] = 217] = "BOX_SINGLE_UP_AND_SINGLE_LEFT";
    Chars[Chars["BOX_SINGLE_DOWN_AND_SINGLE_RIGHT"] = 218] = "BOX_SINGLE_DOWN_AND_SINGLE_RIGHT";
    Chars[Chars["BLOCK_FULL"] = 219] = "BLOCK_FULL";
    Chars[Chars["BLOCK_BOTTOM_HALF"] = 220] = "BLOCK_BOTTOM_HALF";
    Chars[Chars["BLOCK_LEFT_HALF"] = 221] = "BLOCK_LEFT_HALF";
    Chars[Chars["BLOCK_RIGHT_HALF"] = 222] = "BLOCK_RIGHT_HALF";
    Chars[Chars["BLOCK_TOP_HALF"] = 223] = "BLOCK_TOP_HALF";
})(Chars = exports.Chars || (exports.Chars = {}));
